// angular-counter/src/app/counter/counter.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-counter',
  templateUrl: './counter.component.html',
  styleUrls: ['./counter.component.css'],
})
export class CounterComponent {
  count = 0;

  onIncrement() {
    this.count += 1;
  }
  onDecrement() {
    this.count -= 1;
  }
}

<div class="counter-container">
  <h1>{{ count }}</h1>
  <div class="button-container">
    <button type="button" (click)="onDecrement()">-</button>
    <button type="button" (click)="onIncrement()">+</button>
  </div>
</div>

// react-counter/src/components/Counter.tsx
import { useState } from "react";
import "./Counter.css";

function Counter() {
  const [count, setCount] = useState(0);

  const onIncrement = () => setCount(count + 1);
  const onDecrement = () => setCount(count - 1);

  return (
    <div className="counter-container">
      <h1>{count}</h1>
      <div className="button-container">
        <button type="button" onClick={onDecrement}>
          -
        </button>
        <button type="button" onClick={onIncrement}>
          +
        </button>
      </div>
    </div>
  );
}

export default Counter;
